# You are given two strings s and t.
#
# String t is generated by random shuffling string s and then add one more letter at a random position.
#
# Return the letter that was added to t.

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        list2=[]
        for i in t:
            list2.append(i)
        for i in s:
            list2.remove(i)
        return list2[0]


    #solution 2 using hash maps its faster